language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/daemon/"
  - "$HOME/.gradle/native/"
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
script:
  - ./gradlew build test --no-daemon --stacktrace
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest --no-daemon --stacktrace
sudo: false
deploy:
  provider: releases
  api_key:
    secure: P1TZm4YJ8i9rHrgpNoYbDNcYmGz46X8Vn+9e7nmIfMaWzGpgMUqczyPlNRJNcBLo7sqfJliESeqhjdJZcmTwQ/tgbnmYMzU+TaCKrq8KpT+GogOsqu5twUjIw2zXhDH9dEnpMKQcu8Fm2W9kY74r17bn3sZVM+0e4evSzZeb7Q+oUA+IxhTYUR0nD5Narko1jhE14GfAcVvWKMRI55gUElyTbOsWVbL0Y4dN1iYQFIuuiZDRK+4h5eDtw4wZzQhTj4GixArvjEn/bi4wYfEi8js7sllzhbjZBbz6YywfGl4fYRxPbTE9q9Jn462o/kT2alVSujhGdpzdSvRdlT3qu/5v+eFOVnJeWnRzhE2AlXxB9eSNeBTv0qk6yFCd7ezFMTldTLEGtrJZhkufmDbQCtI8t6voU3AMGCwmpw1rn/Q8YKtJku25curf1kPEFGHRyB92ubnXnrx7ccrpa9RdUDXDyE1kv2cKS/tX9P9pg/YPxZibi0xSj4FiBA/vz/gardfsIKdnjzhrFmtInJvz5NjF1MYU1BhPnAY/G9A4mbDD7XGe358H+cqgnkqXmVK3LeA2mjAEfyNPmGqD0Zz2ECGF7aALXJ7lX2QbBcf8JeVSUrGjaHCB0y6o5ztXOVjiTbNAnDG+MQ1QDAF2y/72D0YjWEbBarHMI5//txdp3zs=
  file: "./app/build/outputs/apk/app-release.apk"
  on:
    tags: true
    repo: Shalzz/gocollege-android
after_deploy: "./gradlew publishRelease --no-daemon --stacktrace"
before_install:
- openssl aes-256-cbc -K $encrypted_95a0813dd905_key -iv $encrypted_95a0813dd905_iv
  -in play-service-account-key.json.enc -out play-service-account-key.json -d
env:
  secure: q0isuCInUvB7WLZOmf1pgaCH5o4UJLLtnRuvaGZZW3Ik3BQUzJQxDWW6HFtgTyVl4r3EdF40YLOxkGNYWVy708AXtE6hfyJCkbvYv9LvuZNuLZmX709U725WWOS1n0ZXUUDNWeGurUGrKaoRvl9R1XF66ZXuSk89ZJhBj0j0w8eIW6jhLCQItVy0eLv9WaItf/4qFlcx6D6lAX30+wVuU6GTjT2uoSXkWTxmVPd6FT3O4M+nwAsyyKPHtHSRL5VntfIhgnXqirEg2A3+50oRSc5UzrotypO0gJmFwa6wfZOQUWYrehiHDGOnP7fug/r0RquKMn/yEHNciP9aZlCmbobHPRuorrRGMNWQ+WW8SfbtDsjFJC7VlxHTCRmTQK+zo/gvfZBW+67P7ErOd7Sq8VfoePI9KLB7NhCBfUP/T3mnKw3aN9ZDD/SVDi+fWJz+j/hFgYqnb/75q4bxBP6m18xhh5v1dSH+4G1Xui/LHtUrGiOAzTnPeClcQccxv4eGWIa3pqXAa9BINjN3Z5n7daALU5L+MrJddcVgm5vi944HeyySZSCr1l0T6PGCgAPxwagId3JDClZQnt6G5ysjq90Enq+i29WKJQyy2v8E3Hv2XqdQDgX4FLUt/PP1q97ScRwIXiZchgy+D1MxvXqL0YhyyGuPrDj6rmiOvqcHRjc=
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
